export const conversations = [
    {
        id: 1,
        name: 'Nguyễn Minh',
        lastMessage: 'Cảm ơn bạn đã phản hồi nhanh nhé!',
        timestamp: '2 phút trước',
        role: 'KHÁCH HÀNG',
        unread: 0,
        active: true,
    },
    {
        id: 2,
        name: 'Trần Lan',
        lastMessage: 'Bảng điều khiển mới nhìn đẹp quá!',
        timestamp: '1 giờ trước',
        role: 'NHÓM',
        unread: 1,
        active: false,
    },
    {
        id: 3,
        name: 'Phạm Tuấn',
        lastMessage: 'Tôi sẽ gửi lại cho bạn bảng giá sớm.',
        timestamp: '3 giờ trước',
        role: 'NHÀ CUNG CẤP',
        unread: 0,
        active: false,
    },
    {
        id: 4,
        name: 'Lê Hồng',
        lastMessage: 'Này, bạn rảnh không?',
        timestamp: 'vừa xong',
        role: 'KHÁCH HÀNG',
        unread: 1,
        active: false,
    },
    {
        id: 5,
        name: 'Đặng Nam',
        lastMessage: 'Chúng ta có thể lên lịch họp không?',
        timestamp: 'vừa xong',
        role: 'HỖ TRỢ',
        unread: 1,
        active: false,
    },
]

export const messages = [
    {
        id: 1,
        sender: 'Nguyễn Minh',
        text: 'À đúng rồi! Tôi muốn hỏi về chính sách đổi trả của sản phẩm này.',
        timestamp: '10:45 SA',
        isSender: false,
    },
    {
        id: 2,
        sender: 'Bạn',
        text: 'Câu hỏi hay đấy! Bạn có 30 ngày kể từ ngày nhận hàng để đổi hoặc trả sản phẩm và được hoàn tiền đầy đủ, miễn là sản phẩm còn nguyên vẹn như ban đầu.',
        timestamp: '',
        isSender: true,
    },
    {
        id: 3,
        sender: 'Nguyễn Minh',
        text: 'Tuyệt vời. Thế còn đổi sản phẩm khác thì sao?',
        timestamp: '10:48 SA',
        isSender: false,
    },
    {
        id: 4,
        sender: 'Bạn',
        text: 'Chính sách đổi hàng cũng áp dụng trong 30 ngày. Bạn có thể đổi sang kích cỡ, màu khác hoặc sản phẩm khác có giá trị tương đương hoặc thấp hơn.',
        timestamp: '',
        isSender: true,
    },
    {
        id: 5,
        sender: 'Nguyễn Minh',
        text: 'Tuyệt quá! Bạn hỗ trợ rất nhiệt tình, cảm ơn nhé.',
        timestamp: '10:52 SA',
        isSender: false,
    },
    {
        id: 6,
        sender: 'Bạn',
        text: 'Rất vui vì có thể giúp bạn! Nếu có thêm thắc mắc nào, đừng ngần ngại liên hệ nhé. Chúc bạn một ngày thật tốt lành! 😊',
        timestamp: '',
        isSender: true,
    },
    {
        id: 7,
        sender: 'Nguyễn Minh',
        text: 'Cảm ơn bạn lần nữa, chúc bạn một ngày vui vẻ!',
        timestamp: '10:55 SA',
        isSender: false,
    },
]
